//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace graduation_project_ideas_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IA_DBEntities3 : DbContext
    {
        public IA_DBEntities3()
            : base("name=IA_DBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<members> members { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<professors> professors { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<teamleaders> teamleaders { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
    }
}
