//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace graduation_project_ideas_2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class orders
    {
        public int Id { get; set; }
        public Nullable<int> teamleader_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> professor_id { get; set; }
        public Nullable<int> status { get; set; }

        public virtual professors professors { get; set; }
    }
}
