//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace graduation_project_ideas_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class projects
    {
        internal object teamleaders;

        public int Id { get; set; }
        [Required(ErrorMessage = "d5l asm fkrtk ya 3m :D)...")]
        public string proj_name { get; set; }
        [Required(ErrorMessage = "wsf sri3 kda ya asta :D)...")]
        public string proj_desc { get; set; }
        [Required(ErrorMessage = "htst5dam eh ll fkra de ya m3lam :D)...")]
        public string proj_tools { get; set; }
        public Nullable<int> teamleader_id { get; set; }

        public virtual users users { get; set; }
    }
}
